import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;
import java.awt.*;
import java.util.*;

public class completeStack extends javax.swing.JFrame 
{
    private TicketingSystem ticketingSystem;
    private Stack<CustomerInformation> paidCustomers;

    public completeStack(TicketingSystem ticketingSystem, Stack<CustomerInformation> paidCustomers)
    {
        initComponents();
        this.ticketingSystem = ticketingSystem;
        this.paidCustomers = paidCustomers;
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        DisplayArea = new java.awt.TextArea();
        DisplayButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(178, 224, 244));

        DisplayArea.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        DisplayButton.setBackground(new java.awt.Color(0, 153, 204));
        DisplayButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DisplayButton.setForeground(new java.awt.Color(255, 255, 255));
        DisplayButton.setText("DISPLAY PAID CUSTOMER");
        DisplayButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 102, 102), null, null));
        DisplayButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt) 
                {
                    DisplayButtonActionPerformed(evt);
                }
            });

        ReturnButton.setBackground(new java.awt.Color(255, 153, 0));
        ReturnButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ReturnButton.setForeground(new java.awt.Color(255, 255, 255));
        ReturnButton.setText("BACK");
        ReturnButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 0), new java.awt.Color(255, 102, 0), null, null));
        ReturnButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt) 
                {
                    ReturnButtonActionPerformed(evt);
                }
            });

        ExitButton.setBackground(new java.awt.Color(255, 153, 0));
        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("EXIT");
        ExitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 0), new java.awt.Color(255, 102, 0), null, null));
        ExitButton.addActionListener(new java.awt.event.ActionListener() 
            {
                public void actionPerformed(java.awt.event.ActionEvent evt) 
                {
                    ExitButtonActionPerformed(evt);
                }
            });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(DisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(DisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(DisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                 

    //displaying processed customer from previous class
    public void updatePaidCustomers(StringBuilder paidCustomersText) 
    {
        DisplayArea.setText(paidCustomersText.toString());
    }
    //process to display processed customer
    private void DisplayButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        displayPaidCustomers();
    }
    //displaying processed customer from previous class
    private void displayPaidCustomers()
    {
        StringBuilder displayText = ticketingSystem.getPaidCustomersAsString();
        DisplayArea.setText(displayText.toString());
    }

    //return to previous page
    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        StringBuilder paidCustomersText = ticketingSystem.getPaidCustomersAsString();
        updatePaidCustomers(paidCustomersText);
        ticketingSystem.setVisible(true); // Show the original TicketingSystem
        this.dispose(); // Close the current screen

        System.out.println("Paid Customers in TicketingSystem: " + ticketingSystem.getPaidCustomersAsString());

    }

    //close the program
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {                                           
        System.exit(0);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) 
        {
            java.util.logging.Logger.getLogger(completeStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(completeStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(completeStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(completeStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify                     
    private java.awt.TextArea DisplayArea;
    private javax.swing.JButton DisplayButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}